depend_contracts:
  - name: easyops.api.monitor.alert.GetAlertCount
    version: ^1.0.0
  - name: easyops.api.monitor.alert.GetAlertEventDetail
    version: ^1.0.0
  - name: easyops.api.monitor.alert.GetAlertEventList
    version: ^1.0.0
  - name: easyops.api.monitor.alert.GetNotRecoverAlertEventList
    version: ^1.0.0
  - name: easyops.api.monitor.alert.ListAlertRange
    version: ^1.0.0
  - name: easyops.api.monitor.alert_downtime.GetAllAlertDowntime
    version: ^1.0.0
  - name: easyops.api.monitor.alert_rule.CreateAlertRule
    version: ^1.0.0
  - name: easyops.api.monitor.alert_rule.DeleteAlertRule
    version: ^1.0.0
  - name: easyops.api.monitor.alert_rule.DetailAlertRule
    version: ^1.0.0
  - name: easyops.api.monitor.alert_rule.DetailAlertRuleV4
    version: ^1.0.0
  - name: easyops.api.monitor.alert_rule.DisableAlertRule
    version: ^1.0.0
  - name: easyops.api.monitor.alert_rule.AlertRuleInfo
    version: ^1.0.0
  - name: easyops.api.monitor.alert_rule.GetAlertRuleList
    version: ^1.0.0
  - name: easyops.api.monitor.alert_rule.ListAlertRuleAll
    version: ^1.0.0
  - name: easyops.api.monitor.alert_rule.UpdateAlertRule
    version: ^1.0.0
  - name: easyops.api.monitor.app_health.GetAppHealthConfigV2
    version: ^1.0.0
  - name: easyops.api.monitor.auto_recovery.CreateAutoRecoveryEvent
    version: ^1.0.0
  - name: easyops.api.monitor.collector.GetList
    version: ^1.0.0
  - name: easyops.api.monitor.data_name.CreateMetrics
    version: ^1.0.0
  - name: easyops.api.monitor.data_name.ListMetrics
    version: ^1.0.0
  - name: easyops.api.monitor.influxdb.InfluxdbProxy
    version: ^1.0.0
  - name: easyops.api.monitor.log_search.LogSearch
    version: ^1.0.0
  - name: easyops.api.monitor.translate.ListTranslateData
    version: ^1.0.0
  - name: easyops.api.monitor.translate.ListTranslateRule
    version: ^1.0.0
